### ISSUE TITLE
Formatting is broken

### ISSUE THREAD

**Issue by CubeRanch** [knttnk/snippet-utilities#1]
This extension works well, but the snippet added to the user snippet file has formatting errors. 
The snippet is added to the end of the existing snippets, but it doesn't respect the existing indentation, it doesn't add a trailing comma to the previous snippet block and it has a trailing comma despite being the last block.

**Comment by knttnk** [comment]
Thank you for using SnippetUtilities and creating this issue!

> it doesn't respect the existing indentation

Any example of indentation errors?

I'll fix the other formatting errors.

**Comment by CubeRanch** [comment]
I'm attaching three files. My user snippet php.json before insertion, after insertion and the expected result. I gave them the .txt extension because it looks like you can't upload json. I hope this is good enough.
My bit of code was testing for proper escaping of php's $. You have that right. Almost no one handles that correctly.
Regards
[after_insertion_php.txt](https://github.com/knttnk/snippet-utilities/files/9474679/after_insertion_php.txt)
[before_insertion_php.txt](https://github.com/knttnk/snippet-utilities/files/9474680/before_insertion_php.txt)
[expected_result_php.txt](https://github.com/knttnk/snippet-utilities/files/9474681/expected_result_php.txt)

**Comment by knttnk** [comment]
OK, I understood.
I'll fix it in the next update.

Until the next update, please add a trainling comma for the second-to-last item and press `ctrl`+`alt`+`F` (`ctrl`+`option`+`F`, in Mac) to adjust the indentation.

**Comment by knttnk** [comment]
I think the problem was solved in v0.2.2.
If you encountered a similar issue, feel free to reopen this issue.
