### ISSUE TITLE
Trailing comma on last array element of body

### ISSUE THREAD

**Issue by CubeRanch** [knttnk/snippet-utilities#2]
Hi,
Installed 0.2.0 and tested on a piece of code. I got a trailing comma on the last array element of the body:

		"body": [
			"if ( \\$post instanceof WP_Post ) {",
			"    echo '';",
			"}",
		],

I think that's a problem, right?

**Comment by knttnk** [comment]
Oh, OK.
I'll fix it. Thanks for noting that.

**Comment by knttnk** [comment]
I think the problem was solved.
If you encountered a similar issue, feel free to reopen this issue.
